### ISSUE TITLE
Link to docs for Visual Studio Code from the Azure Services map is broken

### ISSUE THREAD

**Issue by steved0x** [nnmer/azure-services-map#1]
Searching the repo for `https//code.visualstudio.com/docs` shows 2 places that might be the cause.

Clicking the docs link for Visual Studio Code redirects you to here:

`https://docs.microsoft.comhttps//code.visualstudio.com/docs`

Great map by the way, very cool!

![image](https://user-images.githubusercontent.com/1580889/55181597-5965cf00-5162-11e9-90dc-cd387a386e4a.png)

**Comment by nnmer** [comment]
Thanks Steve, fixed
